name: Test

on: [push]

jobs:
  tests:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          ./setup.sh
          pip install -r requirements.dev.txt
      - name: Check formatting
        run: |
          black note_14
      - name: Run application
        run: |
          ./run.sh
