name: Test

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          pip install pylint
          export PYTHONPATH=$PYTHONPATH:$(pwd)/note_14
      - name: Analysing the code with pylint
        run: |
          pylint note_14
      - name: Run application
        run: |
          ./run.sh
