name: Test

on: [push]

jobs:
  tests:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          ./setup.sh
          source .venv/bin/activate
          pip install -r requirements.dev.txt
      - name: Check formatting
        run: |
          source .venv/bin/activate
          black note_14
      - name: Check pylint
        run : |
          source .venv/bin/activate
          pylint note_14
      - name: Run tests
        run: |
          source .venv/bin/activate
          ./test.sh
